### ISSUE TITLE
Update backend schemas according to new information in crawler.

### ISSUE THREAD

**Issue by jpwahle** [jpwahle/cs-insights-backend#19]
**Is your feature request related to a problem? Please describe.**
When the crawler is fully migrated to DBLP, more metadata will be available to the backend.

**Describe the solution you'd like**
We need to extend the backend accordingly.

**Additional context**
With [release](https://github.com/ag-gipp/NLPLand/releases) **after v0.2.1** this issue needs to be addressed to provide full compatibility.

**Comment by trannel** [comment]
Added in #54
