### ISSUE TITLE
Precompute values

### ISSUE THREAD

**Issue by trannel** [jpwahle/cs-insights-backend#49]
**Is your feature request related to a problem? Please describe.**
The `stats` endpoint needs to know certain values, which are much easier to precompute than to compute each query. Currently those values are hardcoded.

- [ ] The smallest and highest year of publication to fill missing years with zeros
- [ ] All possible typeOfPaper to define them in the enum in the schema, and as options for the autocomplete in the frontend
- [ ] All possible fieldsOfStudy to define them in the enum in the schema, and as options for the autocomplete in the frontend
- [ ] All possible access types as options for the autocomplete in the frontend

**Describe the solution you'd like**
Find an automated solution, if possible: MongoDB should precompute those values each time it starts running. The backend can access the values and use them in the correct locations. Or let the crawler write the values to a file each time the crawler runs. The backend can access this file and use the values in the correct locations.

**Describe alternatives you've considered**
If no automated solution can be found, notify the admin about the changes that need to happen.

**Comment by jpwahle** [comment]
I marked this as duplicate just because it won’t be an issue anymore after caching in #89 and fixing database schemas https://github.com/gipplab/cs-insights-backend/issues/90

**Comment by trannel** [comment]
The issues listed here are things that are currently hardcoded, as the issue says, and need to be changend at some point or there will be strange issues, when new data comes in. The idea was to procompute them. Caching and different database schemas will not fix this.

**Comment by jpwahle** [comment]
I see, I will reopen it in this case and make sure that instead of your hardcoded time range implementation, we will query the DB (which then will be cached).
