### ISSUE TITLE
Add structure and packages to README

### ISSUE THREAD

**Issue by trannel** [jpwahle/cs-insights-backend#60]
**Is your feature request related to a problem? Please describe.**
We would like to make is easier for contributing developers to understand our repository. In the frontend we already added a "packages" and "structure" section to the README. These section also exist in the README for this project, but are not complete.

**Describe the solution you'd like**
- [x] Update the "structure" section to include explanations for each directory
- [x] Update the "packages" section to include all notable packages we use and links to them

**Additional context**
Depending on whether or not the feature branch was already merged, only one of the links will work:
Frontend README (feature branch): https://github.com/gipplab/NLP-Land-frontend/tree/add_more_dashboards#repository
Frontend README (main branch): https://github.com/gipplab/NLP-Land-frontend/#repository

**Comment by jpwahle** [comment]
Added in 899b7e423b9c02f78901b58a98ac995825357ef7
