### ISSUE TITLE
TypeScript checks in commit pipeline do not match checks in docker-compose

### ISSUE THREAD

**Issue by trannel** [jpwahle/cs-insights-backend#61]
**Describe the bug**
TypeScript checking fails during the build stage of `docker-compose --env-file=.env.production up --build`, even though all checks passed after the commit. Executing the `npm run build` (with or without `--production`) and `tsc -p .` manually also does not throw any errors. TypeScript appears to be stricter during the docker compose, than in every other place.

**To Reproduce**
1. Run `git checkout dev`
2. Run `git checkout 04127932abd90856f3993f980221ab0ab1f2dbf7`
3. Complete steps in README for production setup including `docker-compose --env-file=.env.production up --build`
4. See error, when the script executes `tsc -p .` during its build stage.
5. Run `npm run build` to see no error
6. Run `tsc -p .` to see no error

Alternative steps to reproduce the behavior:
1. Run `git checkout fix_docker_compose`
2. Navigate to `src/types.ts`
3. Navigate to type `FilterMongo`
4. Remove at least one ` | { $ne: null }`
5. Continue with Step 3 "Complete steps ..." from the first steps to reproduce

**Expected behavior**
The TypeScript checks should already fail in the commit pipeline. Additionally, both `npm run build` and `tsc -p .` should also fail and show the same errors, when I run them in a terminal on my machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/43033261/178138171-f5bb061d-31b2-402e-95bf-fd3efd5e5ee1.png)
These errors should be fixed in #62

**Desktop (please complete the following information):**
 - OS: Linut Mint 20.3
 - Browser: Chrome Version 103.0.5060.114

**Comment by jpwahle** [comment]
I will try to reproduce this behavior on my machine. Probably typescript version mismatch or smth? Before it always passed. We should include testing this in the pipeline, can you open an issue for it? So next time we know which commit broke it.

**Comment by trannel** [comment]
I updated the issue with more information and a second way to reproduce the issue.

TypeScript versions are all 4.7.4 on my machine, except for the express-oas-generator: 
![image](https://user-images.githubusercontent.com/43033261/178236517-9f3aaecb-b6ee-4478-ab82-e2c6221dd52c.png)

During docker compose it is the same: 
![image](https://user-images.githubusercontent.com/43033261/178240459-95143e71-344f-4400-9ecb-bb36772b4840.png)

**Comment by jpwahle** [comment]
The issue is that NODE_ENV is set to `prodocution`in docker which is the expected behavior.
The test pipelines are set to `development`which is the default. Therefore the typescript compiler is not as strict.
