### ISSUE TITLE
Merge controllers of frontend with existing CRUD endpoints.

### ISSUE THREAD

**Issue by jpwahle** [jpwahle/cs-insights-backend#73]
**Is your feature request related to a problem? Please describe.**
The controllers/fe/ subfolder has no value and can be merged with the CRUD endpoints in controllers/

**Describe the solution you'd like**
Merge the endpoints in the top-level directory controllers/

**Comment by trannel** [comment]
I think it makes sense, as the frontend controllers can also be reached under `api/v0/fe` and not the normal route `api/v0/`. This way we also do not not have 2 files with the same name in the same directory.
